FROM golang:latest

WORKDIR /api

COPY ./ /api

ENV CGO_ENABLED=1

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT [ "CompileDaemon", "--build=\"go build cmd/gotestapp/main.go\"", "--command=./main" ]
